spam_control:
  block_users: false
  delete_messages: false
spam_examples:
  - text: Ваш контент — находка!
    score: 0
  - text: в Agile Project Management и в Management 3.0 любят повторять хорошее сравнение с менеджером как садовником. кажется, похоже про то, о чем вы?
    score: -100
  - text: Однажды встретилась книга Билла Вильямса, в которой он объясняет рынки так, что реально начинаешь видеть логику в этом хаосе. С его фишками типа Аллигатора и Фракталов стал точнее ловить моменты входа и выхода. Плюс к этому добавляем различные интенсивы от Криптолоджи, Герчика (видеоуроки) и других, которые помогли когда то собрать стратегию до конца, считаю это мастрид для новичков и профи. Могу подкинуть для изучения, найдёте для себя массу полезного)))
    score: 100
  - text: |
      Пoдeлюcь выгoднoй инфopмaциeй о кpaткосpoчных сдeлкax c crурto
      Высокий дoxoд от 100$ в день
      Все cдeлки coвеpшаете самостоятельно на официальныx pecypсах и плoщaдкax
      Ждy ваши пpeдложения в лc
    score: 100
  - text: Спасибо, интересная информация
    score: 80
  - text: Возможно, это будет полезно. У меня есть видео-курсы по инвестициям в недвижимость (окупаемость, стратегии, заграничная недвижимость, коммерция) и разбор финансовых рынков (фондовый рынок, DeFi). Могу передать этот опыт, для изучения.
    score: 100
  - text: У меня остались видеоуроки от Герчика, Криптолоджи.  Это универсальные пособия, которое подходит и новичкам, и тем, кто хочет узнать  что-то новое.  Охватывает базу (скальпинг,смарт мани,Прайс Экш, волны Эллиотта, Фиббоначчи, ТА,ФА, макроэкономический анализ, ДеФи) + примеры успешных и не успешных сделок. Заинтересованным отправлю.
    score: 100
  - text: |
      🔥НАБ0Р С0ТРУДНИКОВ🔥

        Что мы ВАМ предлагаем 🫵
      ⭕️ Карьерный рост ↗️
      ⭕️ Высокая зарплата от 250.000р в месяц 💰
      ⭕️ Гибкий график работы 🗓
      ⭕️ Оплачиваемая стажировка💸
      ⭕️ Выплаты 2 разы в неделю 🔝
      ⭕️ Опыт не обязателен (всему научим )‼️

      ⬇️ПИШИ И УЗНАЙ БОЛЬШЕ⬇️
      @Anton_pavlovW
    score: 100
  - text: |
      Крипто карты становятся нормой!

      Теперь не надо конвертировать крипту в фиат)
      Можно просто сразу расплачиваться криптой с помощью карты от Bybit

      Раньше она была доступна только для VIP, а теперь для всех)

      Фишки карты:
      - Нет годовой оплаты, нет скрытых комиссий
      - 10% cashback + до 8% apy с Bybit накоплениями
      - Виртуальная карта доступна сразу
      - Apple Pay & Google Pay будут доступны в конце Ноября 2024
      - вы получите $10 за первую транзакцию по карте
      - Не нужен ВИП уровень

      https://www.bybit.com/cards

      Ограничения по резидентству:
      - Карта доступна для НЕ резидентов России, и Белоруси (Украина ок)
      - Карта недоступна для КУС 1 Казахстана, Грузии (и длинного списка не СНГ стран)
      - Картой можно платить только там где принимают MasterCard (не в России и не в Белоруси)



      Подписывайся родной , будет много годного контента
      Спасибо RicHard -❤️
      @RicHard
    score: 100
  - text: Всем привет, остались кypcы пo недвижимости и флиппингу, если кому интepecно, напишите мне в лс.
    score: 100
  - text: Зачем на борту человек, который не дополняет команду своими уникальными знаниями, делами, опытом или еще чем то? Это не член команды - это балласт, который в итоге все равно придется в шторм сбросить. Не про конкретного человека речь, я не знаю всего контекста, просто мысли вслух. Если ошибся один раз и при втором подходе включаешь девочку, ну это как то странно)))
    score: -100
  - text: Вы имеете в виду поднять общий уровень корп культуры и докрутить всем (?!) майндсет? Что это создаст атмосферу, в которой действия сотрудников будут максимально «правильными», этичными и эффективными?
    score: -100
  - text: Поменять майндсет и не вырабатывать шлаковые эмоции.
    score: -100
  - text: Понятной не стало) А можно конкретный пример из жизни?
    score: -100
  - text: А как же подавленные эмоции?! Это влияет на мое здоровье, поэтому я себя веду естественно в рамках приличия
    score: -100
  - text: Так держать ✅
    name: Александр Пономарев
    bio: <пусто>
    score: -100
  - text: |
      У меня осталась информация про скальпинг стратегии , уверен будет полезно изучить  новичкам и тем кто давно в сфере трейдинга, лично мне когда-то принесло пользу. В данном материале объясняется  про   уровни поддержки и сопротивления, двойное дно, тройное дно, и тд. в дополнение информация про Свинг-трейдинг.
      Кто заинтересован, готов предоставить.
    score: 100
    name: sit
    bio: <пусто>

help_text: |
  🤖 Приветствую, человек! Я - нейромодератор, твой защитник от спама в Telegram-группах.

  💪 Что я умею:
  • Анализирую все сообщения в группах
  • Удаляю спам-сообщения
  • Веду учет проверенных пользователей
  • Уведомляю админов о найденном спаме

  💰 Стоимость услуг:
  • Проверка сообщения от нового пользователя: 1 звезда
  • Все остальные операции бесплатно

  🛡 Как начать защиту:
  1. Добавь меня в группу
  2. Сделай администратором
  3. Готово! Я начну защищать группу

  ⚙️ Что модерируется:
  • Текстовые сообщения
  • Изображения с текстом
  • Ссылки
  • Пересланные сообщения
  • Медиа с подписями

  ❌ Что не модерируется:
  • Системные сообщения
  • Сообщения админов
  • Сервисные уведомления
  • Закрепленные сообщения
  • Опросы
  • Сообщения без текста

  💡 Доступные команды:
  /start - показать это сообщение
  /help - показать это сообщение
  /buy - купить звезды
  /stats - показать баланс и статус групп

  🔧 Техподдержка: @leshchenko1979
