spam_control:
  block_users: false  # Блокировка пользователей отключена

help_text: |
  🤖 Приветствую, человек! Я - нейромодератор, твой защитник от спама в Telegram-группах.

  💪 Что я умею:
  • Анализирую все сообщения в группах
  • Удаляю спам-сообщения (если все админы включили режим удаления)
  • Веду учет проверенных пользователей
  • Уведомляю админов о найденном спаме

  💰 Стоимость услуг:
  • Проверка сообщения от нового пользователя: 1 звезда
  • Все остальные операции бесплатно

  🛡 Как начать защиту:
  1. Добавь меня в группу
  2. Сделай администратором
  3. Готово! Я начну защищать группу

  ⚙️ Что модерируется:
  • Текстовые сообщения
  • Изображения с текстом
  • Ссылки
  • Пересланные сообщения
  • Медиа с подписями

  ❌ Что не модерируется:
  • Системные сообщения
  • Сообщения админов
  • Сервисные уведомления
  • Закрепленные сообщения
  • Опросы
  • Сообщения без текста

  💡 Доступные команды:
  /start - показать это сообщение
  /help - показать это сообщение
  /buy - купить звезды
  /stats - показать баланс и статус групп
  /mode - переключить режим (удаление/уведомления)

  🔧 Техподдержка: @leshchenko1979
