spam_control:
  block_users: false  # Блокировка пользователей отключена

help_text: |
  🤖 Приветствую, человек! Я - нейромодератор, твой защитник от спама в Telegram-группах.

  💪 Что я умею:
  • Анализирую все сообщения в группах с помощью ИИ
  • Удаляю спам-сообщения (если все админы включили режим удаления)
  • Веду учет проверенных пользователей
  • Уведомляю админов о найденном спаме
  • Учусь на ваших примерах спама

  💰 Стоимость услуг:
  • Проверка сообщения от нового пользователя: 1 звезда
  • Проверенные пользователи: бесплатно
  • Покупка пакетов по 100 звезд

  🛡 Как начать защиту:
  1. Добавь меня в группу
  2. Сделай администратором
  3. Готово! Я начну защищать группу

  ⚙️ Что модерируется:
  • Текстовые сообщения
  • Изображения с текстом
  • Ссылки
  • Пересланные сообщения
  • Медиа с подписями

  ❌ Что не модерируется:
  • Системные сообщения
  • Сообщения админов
  • Сервисные уведомления
  • Закрепленные сообщения
  • Опросы
  • Сообщения без текста

  🎯 Как работает защита:
  • Анализирую сообщения с помощью ИИ
  • Оцениваю вероятность спама в процентах
  • При score > 50% - считаю сообщение спамом
  • При score ≤ 50% - добавляю в белый список

  📚 Обучение бота:
  • Пересылайте мне подозрительные сообщения
  • Отмечайте их как "Спам" или "Не спам"
  • Я буду учиться на ваших примерах
  • Чем больше примеров - тем точнее защита

  💡 Доступные команды:
  /start - показать это сообщение
  /help - показать это сообщение
  /buy - купить пакет из 100 звезд
  /stats - показать баланс и статус групп
  /mode - переключить режим (удаление/уведомления)

  🔧 Техподдержка: @leshchenko1979
